<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Calendar\Controller\CalendarController'        => __DIR__ . '/src/Calendar/Controller/CalendarController.php',
    'Calendar\Controller\CalendarManagerController' => __DIR__ . '/src/Calendar/Controller/CalendarManagerController.php',
    'Calendar\Entity\EntityAbstract'                => __DIR__ . '/src/Calendar/Entity/EntityAbstract.php',
    'Calendar\Entity\EntityInterface'               => __DIR__ . '/src/Calendar/Entity/EntityInterface.php',
    'Calendar\Form\CreateObject'                    => __DIR__ . '/src/Calendar/Form/CreateObject.php',
    'Calendar\Form\FilterCreateObject'              => __DIR__ . '/src/Calendar/Form/FilterCreateObject.php',
    'Calendar\Form\ObjectFieldset'                  => __DIR__ . '/src/Calendar/Form/ObjectFieldset.php',
    'Calendar\Module'                               => __DIR__ . '/src/Calendar/Module.php',
    'Calendar\Service\CalendarService'              => __DIR__ . '/src/Calendar/Service/CalendarService.php',
    'Calendar\Service\FormService'                  => __DIR__ . '/src/Calendar/Service/FormService.php',
    'Calendar\Service\FormServiceAwareInterface'    => __DIR__ . '/src/Calendar/Service/FormServiceAwareInterface.php',
    'Calendar\Service\ServiceAbstract'              => __DIR__ . '/src/Calendar/Service/ServiceAbstract.php',
    'Calendar\Service\ServiceInterface'             => __DIR__ . '/src/Calendar/Service/ServiceInterface.php',
    'Calendar\Version\Version'                      => __DIR__ . '/src/Calendar/Version/Version.php',
    'Calendar\View\Helper\CalendarLink'             => __DIR__ . '/src/Calendar/View/Helper/CalendarLink.php',
    'Calendar\Service\ModuleOptionAwareInterface'   => __DIR__ . '/src/Calendar/Service/ModuleOptionAwareInterface.php',
    'ModuleOptionAwareInterface'                    => __DIR__ . '/src/Calendar/Controller/ControllerInitializer.php',
    'Calendar\Options\CalendarOptionsInterface'     => __DIR__ . '/src/Calendar/Options/CalendarOptionsInterface.php',
    'Calendar\Options\ModuleOptions'                => __DIR__ . '/src/Calendar/Options/ModuleOptions.php',
);
