<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'calendar/calendar-community/calendar' => __DIR__ . '//view/calendar/calendar-community/calendar.twig',
    'calendar/calendar-community/overview' => __DIR__ . '//view/calendar/calendar-community/overview.twig',
);
