<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'calendar/calendar-community/calendar'        => __DIR__ . '//view/calendar/calendar-community/calendar.twig',
    'calendar/calendar-community/overview'        => __DIR__ . '//view/calendar/calendar-community/overview.twig',
    'calendar/calendar-community/review-calendar' => __DIR__ . '//view/calendar/calendar-community/review-calendar.twig',
    'calendar/calendar-document/document'         => __DIR__ . '//view/calendar/calendar-document/document.twig',
    'calendar/partial/pagination-control'         => __DIR__ . '//view/calendar/partial/pagination-control.twig',
);
