<?php
_("txt-calendar-sequence-explanation");
_("txt-date-from");
_("txt-date-from-explanation");
_("txt-date-end");
_("txt-date-end-explanation");
_("txt-calendar-description-explanation");
_("txt-image-url-explanation");
_("txt-calendar-url-explanation");
_("txt-calendar-explanation");
_("txt-draft");
_("txt-tentative");
_("txt-location-explanation");