<?php
_("txt-presence-status-tentative-hover-text");
_("txt-presence-status-decline-hover-text");
_("txt-presence-status-accept-hover-text");
_("txt-remove");
_("txt-reset");
_("txt-select-all");
_("txt-add");
_("txt-remove-all");
_("txt-add-all");
_("txt-subtract");
